name: dflooted_flutter_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/maps/
    - assets/images/agents/

  fonts:
    - family: DeltaForce
      fonts:
        - asset: assets/fonts/deltaforce.ttf
